project:
  type: website
  
website:
  title: "jnomhgn"
  site-url: https://jnomhgn.github.io
  navbar:
    background: primary
    search: true
    left:
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/
  page-footer: 
    right: 
      - icon: github
        href: https://github.com
    center: 
      - text: This website was built with Quarto
        href: https://quarto.org

format:
  html:
    include-in-header: header.html
    theme: light.scss
    css: styles.css
    toc: true
    page-layout: full
    comments: 
      giscus: 
        loading: lazy
        input-position: top
        repo: jnomhgn/jnomhgn.github.io
        reactions-enabled: true
        mapping: title
        category: "Announcements"

editor: visual

resources: 
  - robots.txt